### ISSUE TITLE
Reconstructed.tar.xz error

### ISSUE THREAD

**Issue by Ibrahimatef** [GuillaumeRochette/PanopticProcessing#2]
Hi, Thanks for your great work
I am trying to run your repo [HumanViewSynthesis](https://github.com/GuillaumeRochette/HumanViewSynthesis) using `infer_virtual.py`
so, I downloaded one video from panoptic data using this command `./scripts/getData.sh 171026_pose3 0 1` and followed your processing instructions and edited `metadata.py` according to the downloaded video but I get  this error when trying to run `bash list_reconstruction_3d.sh` 

```
{'calibration': PosixPath('/content/Panoptic/171026_pose3/cameras.json'),
 'max_iterations': 500,
 'min_views': 1,
 'pattern': '([0-9]{12})+',
 'poses_2d_dir': PosixPath('/content/Panoptic/171026_pose3/Poses/2D/BODY_135'),
 'poses_2d_suffix': '.tar.xz',
 'poses_3d': PosixPath('/content/Panoptic/171026_pose3/Poses/3D/BODY_135/Reconstructed.tar.xz'),
 'threshold': 0.25}
100% 7995/7995 [00:03<00:00, 2449.52it/s]
  0% 15/1079190 [00:00<11:49, 1520.34it/s]
Traceback (most recent call last):
  File "BODY_135.py", line 99, in <module>
    verbose=True,
  File "/content/Reconstruction3D/geometry/reconstruction.py", line 108, in perspective_reconstruction
    m_[:] = 0.0
IndexError: slice() cannot be applied to a 0-dim tensor.
```

Could you help me to fix it?

**Comment by GuillaumeRochette** [comment]
Hi @Ibrahimatef,
In order to perform 3D reconstruction, you need to download videos from multiple viewpoints.
The command `./scripts/getData.sh 171026_pose3 0 1` downloads the video of a single viewpoint.
You need at least 2 views to run the 3D reconstruction algorithm, however the more the better usually, as estimated 2D keypoints are not pixel accurate.
I recommend you to download all the 31 videos to reproduce the data used in the paper, using the following command `./scripts/getData.sh 171026_pose3 0 31`, as indicated in the README.
Best,
Guillaume
